/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAuditCard: typeof import('./../components/sidebar/AiAuditCard.vue')['default']
    AiStatusBadge: typeof import('./../components/common/AiStatusBadge.vue')['default']
    AnnouncementCard: typeof import('./../components/sidebar/AnnouncementCard.vue')['default']
    AnnouncementPopup: typeof import('./../components/AnnouncementPopup.vue')['default']
    AppHeader: typeof import('./../components/header/AppHeader.vue')['default']
    AuthDialog: typeof import('./../components/auth/AuthDialog.vue')['default']
    AutoFitText: typeof import('./../components/common/AutoFitText.vue')['default']
    BadgeIcon: typeof import('./../components/common/BadgeIcon.vue')['default']
    BottleSkeleton: typeof import('./../components/common/BottleSkeleton.vue')['default']
    BottomTabBar: typeof import('./../components/BottomTabBar.vue')['default']
    CircleDetailSkeleton: typeof import('./../components/common/CircleDetailSkeleton.vue')['default']
    CommentItem: typeof import('./../components/comment/CommentItem.vue')['default']
    CommentList: typeof import('./../components/comment/CommentList.vue')['default']
    Dialog: typeof import('./../components/native/Dialog.vue')['default']
    DownloadAppButton: typeof import('./../components/DownloadAppButton.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmptyState: typeof import('./../components/common/EmptyState.vue')['default']
    HotPostsCard: typeof import('./../components/sidebar/HotPostsCard.vue')['default']
    Icon: typeof import('./../components/native/Icon.vue')['default']
    ImageViewer: typeof import('./../components/common/ImageViewer.vue')['default']
    InfiniteScrollFooter: typeof import('./../components/common/InfiniteScrollFooter.vue')['default']
    InviteCodeDialog: typeof import('./../components/auth/InviteCodeDialog.vue')['default']
    MarkdownText: typeof import('./../components/common/MarkdownText.vue')['default']
    Pagination: typeof import('./../components/common/Pagination.vue')['default']
    PostCard: typeof import('./../components/post/PostCard.vue')['default']
    PostDetailDialog: typeof import('./../components/admin/PostDetailDialog.vue')['default']
    PostDetailSkeleton: typeof import('./../components/post/PostDetailSkeleton.vue')['default']
    PostEditor: typeof import('./../components/post/PostEditor.vue')['default']
    PostImages: typeof import('./../components/post/PostImages.vue')['default']
    PostListSkeleton: typeof import('./../components/post/PostListSkeleton.vue')['default']
    ProfileCard: typeof import('./../components/sidebar/ProfileCard.vue')['default']
    ProfileSkeleton: typeof import('./../components/common/ProfileSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Segmented: typeof import('./../components/native/Segmented.vue')['default']
    Select: typeof import('./../components/native/Select.vue')['default']
    SideMenu: typeof import('./../components/sidebar/SideMenu.vue')['default']
    StatsCard: typeof import('./../components/sidebar/StatsCard.vue')['default']
    Switch: typeof import('./../components/native/Switch.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
