"""add action index to operation_logs

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-26 11:25:12.650239

T3-2: operation_logs 补索引。
- action: 新增索引（按 action 过滤性能提升）

注：user_id 索引已由 0001_initial 在建表时创建（model 中 user_id 已有 index=True），
无需在 0002 重复添加。老库若缺 user_id 索引属 schema drift，由 alembic_helper.ensure_schema
在 dev 兜底用 create_all 修复，生产环境应执行 0001 重建。
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operation_logs_action'), ['action'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operation_logs_action'))

    # ### end Alembic commands ###
