plugins {
    id 'com.android.application'
}

android {
    namespace 'com.liyang.community'
    compileSdk 36
    buildToolsVersion '36.1.0'

    signingConfigs {
        release {
            storeFile rootProject.file('liyang-release.keystore')
            storePassword rootProject.file('keystore-password.txt').text.trim()
            keyAlias 'liyang'
            keyPassword rootProject.file('keystore-password.txt').text.trim()
        }
    }

    defaultConfig {
        applicationId 'com.liyang.community'
        minSdk 26
        targetSdk 36
        versionCode 3
        versionName '1.0.2'
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
